language: node_js
node_js:
  - stable
  - lts/*
script:
  - "yarn run lint"
  - "yarn run check-format"
  - "yarn upgrade eslint@2 && yarn test"
  - "yarn upgrade eslint@3 && yarn test"
  - "yarn upgrade eslint@4 && yarn test"
