language: node_js
node_js:
  - 4
  - 6
  - 8
script:
  - npm run lint
  - npm run check-format
  - npm install eslint@2 && npm test
  - npm install eslint@3 && npm test
  - npm install eslint@4 && npm test
