language: node_js
node_js:
  - stable
  - lts/*
script:
  - "npm install eslint@2 && npm test"
  - "npm install eslint@3 && npm test"
  - "npm install eslint@4.0.0-beta.0 && npm test"
  - "npm run test"
  - "npm run check-format"
