language: node_js

matrix:
  include:
    - node_js: 8
      env: ESLINT_VERSION=latest
    - node_js: 10
      env: ESLINT_VERSION=latest
    - node_js: 12
      env: ESLINT_VERSION=latest RUN_LINT=true RUN_INTEGRATION=true
    - node_js: 12
      env: ESLINT_VERSION=4.7 RUN_INTEGRATION=true

script:
  - if [[ $RUN_LINT = true ]]; then npm run lint; fi
  - if [[ $RUN_INTEGRATION = true ]]; then ./tools/integration-tests.bash; fi
  - npm install eslint@$ESLINT_VERSION
  - npm test
